### ISSUE TITLE
关于gradio示例

### ISSUE THREAD

**Issue by nekocar** [phbst/tinyRAG#4]
我在运行gradio段代码测试的时候总是报错 “request time out”，无法解决
gradio是直接 pip 安装的，请问是否是这方面的原因？

非常感谢您的开源代码的付出，我学习到了很多

**Comment by phbst** [comment]
您好，如果成功启动了gradio的demo，gradio应该没问题。默认使用的model是openai的gpt35,所以猜测是没有科学上网工具？或者是否配置OpenAI以及质谱的API_KEY。
